---
title: "Homework2"
author: "Yingshan Li (7937790)"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
abalone <- read.csv(file = "abalone.csv")
```


```{r, include = FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(tidymodels)
library(ISLR)
```


Question 1


```{r}
abalone2 <- abalone %>%
  mutate(age = abalone$rings + 1.5)
```

Question 2
```{r}
set.seed(2231)

abalone_split <- initial_split(abalone2, prop = 0.80, strata = age)

abalone_train <- training(abalone_split)
abalone_test <- testing(abalone_split)
```

Question 3
```{r}
abalone_recipe <- recipe(age ~ type + longest_shell + diameter + height + whole_weight + shucked_weight + viscera_weight + shell_weight, data = abalone_train) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_interact(~ starts_with("type"):shucked_weight + longest_shell:diameter + shucked_weight:shell_weight) %>% 
  step_center(all_predictors()) %>% 
  step_scale(all_predictors())

```
 
Question 4
```{r}
lm_mod <- linear_reg() %>% 
  set_engine("lm")
```

Question 5
```{r}
lm_wflow <- workflow() %>% 
  add_model(lm_mod) %>% 
  add_recipe(abalone_recipe)
```


Question 6
fit the linear model
```{r}
lm_fit <- fit(lm_wflow, abalone_train)
```

```{r}
lm_fit %>% 
  extract_fit_parsnip() %>% 
  tidy()
```

```{r}
Preicted_age <-predict(lm_fit, data.frame(type = "F", longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1))
Preicted_age
```

Question 7
```{r}
abalone_metrics <- metric_set(rmse, rsq, mae)

```

```{r}
abalone_train_res <- predict(lm_fit, new_data = abalone_train %>% select(-age, -rings))
abalone_train_res %>% 
  head()
```
```{r}
abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))
abalone_train_res %>% 
  head()
```

```{r}
abalone_metrics(abalone_train_res, truth = age, estimate = .pred)
```
$R^2$ : 0.553. 55.3% of the variation in the response can be explained by the predictors.  





